# Generated by Django 4.2.3 on 2023-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_image', models.TextField(default='')),
                ('company_donation_cm', models.IntegerField(default=0)),
                ('company_donation_km', models.IntegerField(default=0)),
                ('company_donation_mil', models.IntegerField(default=0)),
                ('last_updated_mil', models.FloatField(default=0)),
            ],
        ),
    ]
